- public/index.html
- src/App.js
- src/actions/buyerActions.js
- src/actions/cartActions.js
- src/actions/mediaActions.js
- src/actions/productActions.js
- src/actions/sellerProductActions.js
- src/actions/types.js
- src/actions/userActions.js
- src/components/CreateProduct.js
- src/components/CustomerProfile.js
- src/components/LoginComponent.js
- src/components/SellerProducts.js
- src/components/SellerShopRegister.js
- src/components/SignUpComponent.js
- src/components/pages/Cart.js
- src/components/pages/Home.js
- src/components/pages/LocalHome.js
- src/components/pages/Product.js
- src/components/pages/ProductItem.js
- src/index.css
- src/reducers/buyerReducer.js
- src/reducers/cartReducer.js
- src/reducers/index.js
- src/reducers/mediaReducer.js
- src/reducers/productReducer.js
- src/reducers/sellerProductReducer.js
- src/reducers/userReducer.js
- redux changes for buyer and seller home screen, add to cart and review and images
> Redux changes

- src/components/CreateProduct.js
> categorylist

- src/App.js
- src/actions/sellerProductActions.js
- src/components/CreateProduct.js
- src/components/ListProducts.js
- src/components/SellerProducts.js
- added redux changes for seller product
> Redux changes2

- src/components/ListProducts.js
- src/components/SellerProducts.js
- src/index.css
> Shop Details HomePage UI

- src/App.js
- src/components/ShopView.js
- src/components/pages/Product.js
> Add New Product Review

- src/actions/cartActions.js
- src/actions/orderActions.js
- src/actions/types.js
- src/components/pages/Cart.js
- src/components/pages/Home.js
- src/components/pages/StripeButton.js
- src/reducers/cartReducer.js
- src/reducers/index.js
- src/reducers/orderReducer.js
> Temp branch2

- src/actions/orderActions.js
- src/components/ListProducts.js
- src/components/OrdersPlaced.js
- src/components/SellerProducts.js
- src/components/SellerShopRegister.js
- src/components/pages/StripeButton.js
- src/index.css
> added order details change

- src/App.js
- src/components/ShopProducts.js
- src/components/ShopView.js
- src/components/pages/Product.js
> Shop Page View for Buyer

- src/components/OrdersPlaced.js
- src/components/pages/StripeButton.js
> Order details

- src/components/ListProducts.js
- src/components/SellerShopRegister.js
> Corrected Shop ListProducts Rendering

- src/components/NavbarSeller.js
- src/components/pages/StripeButton.js
> removed tracking and added seller id

- src/components/SellerShopRegister.js
- src/components/ShopProducts.js
> New react branch

- src/components/SellerShopRegister.js
> Reverted re render code

- src/components/SellerShopRegister.js
> Fixed Re render Issue

- src/components/SellerProfile.js
- src/components/ShopView.js
- src/index.css
> Seller Profile UI Changes

- src/actions/productActions.js
- src/components/pages/Product.js
> New Review Redux Wiring

- src/components/CreateProduct.js
> Added condition to Register Shop before Adding products

- src/App.js
- src/actions/orderActions.js
- src/components/CompletedOrders.js
- src/components/MainHome.js
- src/components/NavbarSeller.js
- src/components/OpenOrders.js
- src/components/Orders.js
> Order fulfill

- src/actions/billingActions.js
- src/actions/types.js
- src/components/SellerProfile.js
- src/components/pages/Home.js
- src/components/pages/Product.js
- src/reducers/billingReducer.js
- src/reducers/index.js
> seller billing info added

- src/actions/sellerProductActions.js
- src/components/CreateProduct.js
- src/components/ListProducts.js
- src/components/SellerProducts.js
> edit and delete seller

- src/components/pages/Home.js
- src/index.css
> Alignment of searchbar corrected

- src/actions/sellerProductActions.js
- src/components/SellerProfile.js
> Shop upload more images redux wiring

- src/components/pages/Filter.js
- src/components/pages/Home.js
- src/components/pages/Product.js
> React frontend branch

- public/index.html
- src/auth_details_buyer.js
- src/auth_details_seller.js
> updated redirection url

- src/App.js
- src/components/BuyerComponents/BuyerHomePage.js
- src/components/SellerComponents/SellerHomePage.js
> secured route

- src/components/pages/Product.js
> Added $ sign
